<?php
/*
class People
{
    public $name;
    public $age;


    public function __construct($name, $age){
        $this->name = $name;
        $this->age = $age;

    }


    public function go(){
        echo "$this->name Иду" . "</br>";
        $this->age++;
        echo $this->age;
    }
}

class homeAnimal
{
    public $name;
    public $age;
    public $color;

    public function showName(){
        echo "Моего домашнего питомца зовут " . "$this->name" . "</br>";
    }

    public function showAge(){
        echo "Ему" . " $this->age
        " . " лет</br>";
    }

    public function showColor(){
        echo "У него необычный цвет - " . " $this->color" . "</br>";
    }

    public function __construct($name, $age, $color){
        $this->name = $name;
        $this->age = $age;
        $this->color = $color;

    }
}*/

class My_parent
{
    private $name;
    public $age;

    public function __construct($name, $age) {
        $this->name = $name;
        $this->age = $age;
    }

    public function sleep(){
        echo "sleep $this->name";
    }
}

class My_child extends My_parent
{
    public $school;
    public function __construct($name, $age, $school)
    {
        parent::__construct($name, $age);
        $this->school = $school;
    }
    public function sleep()
    {
        echo parent::sleep() . " and school {$this->school}"; // TODO: Change the autogenerated stub
    }
}